name: arri_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/modiimedia/arri

environment:
    sdk: ^3.0.5

dependencies:
    http: ^1.1.0

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
