[workspace]
members = ["rust-client", "rust-codegen-reference"]

resolver = "2"

[workspace.dependencies]
chrono = "0.4"
reqwest = { version = "0.12", features = ["stream"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
